SEG2105-Group/JobZi

- .idea/misc.xml
- app/src/main/res/layout/activity_login.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Just a template interface, no functions were done.
> Added login activity template.

- app/build.gradle
- app/src/androidTest/java/com/arom/jobzi/ExampleInstrumentedTest.java
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/arom/jobzi/MainActivity.java
- app/src/main/res/layout/activity_main.xml
- app/src/test/java/com/arom/jobzi/ExampleUnitTest.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> Renamed packages to com.arom.jobzi

- app/src/main/java/com/arom/jobzi/util/AccountType.java
- app/src/main/java/com/arom/jobzi/util/AccountsManager.java
> Working on account management system.

- app/src/main/res/layout/activity_welcome.xml
> fiexed aziz's mistake

- app/src/main/java/com/arom/jobzi/LoginActivity.java
- app/src/main/java/com/arom/jobzi/SignupActivity.java
- app/src/main/java/com/arom/jobzi/user/User.java
> Working on preventing addition of multiple admins.

- .idea/misc.xml
- app/src/main/java/com/arom/jobzi/SignupActivity.java
Basically if user with either the specified email or username already exists they will not be created again.
> Added functionality to prevent duplicate users.

- .idea/misc.xml
- app/src/main/java/com/arom/jobzi/ServiceEditorActivity.java
- app/src/main/java/com/arom/jobzi/service/Service.java
- app/src/main/res/layout/activity_service_editor.xml
- Actually added the service editor service and corresponding layout file.
> Adding service adding/editing functionality.

- .gitignore
- app/google-services.json
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/layout/activity_signup.xml
- app/src/test/java/com/arom/jobzi/TestClass.java
This should fix issue with failing CircleCI builds.
> Added google-services.json.

- app/src/main/java/com/arom/jobzi/fragment/ServiceListFragment.java
- app/src/main/java/com/arom/jobzi/fragment/UserListFragment.java
- app/src/main/java/com/arom/jobzi/util/Util.java
- The lists were not updating before because, although the respective List object was being updated (added to/removed from) when the firebase database updates, the array adapter for it was not being notified of these changes. Now it is.
> Fixed MAJOR issue with array adapters (user and service).

- app/src/main/java/com/arom/jobzi/AdminActivity.java
- app/src/main/java/com/arom/jobzi/ServiceEditorActivity.java
- app/src/main/java/com/arom/jobzi/fragment/ServiceListFragment.java
- app/src/main/res/layout/activity_service_editor.xml
- app/src/main/res/layout/service_item.xml
- app/src/main/res/values/strings.xml
> Implemented auto-filling of fields in ServiceEditorActivity and improved user-friendliness.

- .idea/misc.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/arom/jobzi/util/Util.java
- Again, re-verted to jdk 1.8.
>  Added logout method to Util class.

- app/src/main/java/com/arom/jobzi/user/UserArrayAdapter.java
- app/src/main/res/layout/user_item.xml
- Looks much nicer now.
- Displays account type on the side as well.
This fixes issue #89.
> Improved user list layout.

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/arom/jobzi/LoginActivity.java
- app/src/main/java/com/arom/jobzi/MainActivity.java
- app/src/main/java/com/arom/jobzi/util/Util.java
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- If it finds a user is logged in, it will direct them to their appropriate activity. Otherwise, it will go to the login activity.
> Added a proper main activity which displays that it is loading.

- app/src/main/java/com/arom/jobzi/ServiceEditorActivity.java
- app/src/main/res/layout/activity_user.xml
- app/src/main/res/values/strings.xml
- Improved the string displayed at the top.
- Changed tools:context of activity_user.xml.
> Fixed service editor validation. Issue #113.

- app/src/main/res/layout/activity_user.xml
> Fixed UserActivity scrolling issue.

- app/src/main/java/com/arom/jobzi/LandingActivity.java
- app/src/main/res/layout/navigation_header.xml
- app/src/main/res/menu/drawer_menu.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
> Improved navigation header.

- app/src/main/AndroidManifest.xml
> Made keyboard appear automatically in ServiceEditorActivity.

- app/src/main/java/com/arom/jobzi/LandingActivity.java
- app/src/main/java/com/arom/jobzi/ServiceEditorActivity.java
- app/src/main/java/com/arom/jobzi/ServiceSelectorActivity.java
- app/src/main/java/com/arom/jobzi/fragment/serviceprovider/ServiceProviderServicesFragment.java
When the admin deletes a service, it needs to be removed the from the list of provided services for every service provider that provides the specific service.
> Unable to fix deleted services issue.

- app/src/main/java/com/arom/jobzi/ProfileActivity.java
- Was previously accessing the wrong database to try and store the user in.
- Added saving of user-specific profile as well.
> Fixed profile activity not properly saving user information.

- .idea/misc.xml
- app/src/main/java/com/arom/jobzi/fragment/AdminFragment.java
- app/src/main/java/com/arom/jobzi/fragment/admin/AdminUsersFragment.java
- app/src/main/res/layout/fragment_user_list.xml
- Just to stay consistent with the conventions set by the service provider fragments.
> Refactored fragment to display the user list to the admin.

- .idea/misc.xml
- app/src/main/java/com/arom/jobzi/profile/ServiceProviderProfile.java
- app/src/main/java/com/arom/jobzi/util/RatingsUtil.java
- app/src/main/java/com/arom/jobzi/util/UserProfileUtil.java
> Added rating field in service provider profile.

- app/src/main/java/com/arom/jobzi/util/SearchUtil.java
- Simple had the logic wrong in.
> Actually fixed searching by availability.

- app/src/main/java/com/arom/jobzi/util/SearchUtil.java
Maybe for real this time. Same 2 lines, double checked the logic, should be good now. Also formatted the SearchUtil class.
> Fixed searching functionality.

- app/src/androidTest/java/com/arom/jobzi/Deliverable3Test.java
> Finally added unit tests for deliverable 3.
